---
# tasks file for centos_packages
      - name: Install required packages
        yum:
          name: " {{ item }} "
          state: present
        with_items:
          -  python 
          -  python-setuptools
          -  epel-release
          -  python-devel
          -  python-pip
          -  mysql-devel
          -  MySQL-python
          -  initscripts
  